### ISSUE TITLE
Problem with local storage installation.

### ISSUE THREAD

**Issue by Lukman-Abdulrahman** [mrbazzan/pynation#13]
Create setup.py file to enable `pip install -e .`, as it only works with setuptools based build

**Comment by Lukman-Abdulrahman** [comment]
Nevermind.

> I would like to work on this issue.



> Create setup.py file to enable `pip install -e .`, as it only works with setuptools based build

Nevermind. I upgraded pip; and it works fine.

**Comment by mrbazzan** [comment]
Okay.!
